In [1]:
import tensorflow as tf

In [2]:
graph1 = tf.Graph()

In [5]:
with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')

In [6]:
a

<tf.Tensor 'constant_a_1:0' shape=(1,) dtype=int32>

In [7]:
#Printing the value of a
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


In [8]:
with graph1.as_default():
    c = tf.add(a,b)

In [9]:
with tf.Session(graph = graph1) as sess:
    result = sess.run(c)
    print(result)

[5]


In [11]:
graph2 = tf.Graph()
with graph2.as_default():
    matrix_one = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
    matrix_two = tf.constant([[2,2,2],[3,3,3],[4,4,4]])
    
    add_one_operation = tf.add(matrix_one, matrix_two)
    add_two_operation = matrix_one + matrix_two
    
with tf.Session(graph = graph2) as sess:
    result = sess.run(add_one_operation)
    print("Defined using tensorflow function: ")
    print(result)
    result = sess.run(add_two_operation)
    print("Defined using normal expressions: ")
    print(result)

Defined using tensorflow function: 
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]
Defined using normal expressions: 
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]


In [21]:
v = tf.Variable(0)

In [13]:
update = tf.assign(v, v+1)

In [15]:
init_op = tf.global_variables_initializer()

In [16]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(v))
    for _ in range(3):
        sess.run(update)
        print(sess.run(v))

0
1
2
3


In [17]:
a = tf.placeholder(tf.float32)

In [18]:
b = a*2

In [19]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict={a:3.5})
    print(result)

7.0
